-- Family ticket reminders. This migration intentionally touches only the
-- ticket-specific schedules tables in the shared Supabase project.

create extension if not exists pg_net with schema extensions;
create extension if not exists pg_cron;

do $$
begin
  if exists (
    select 1 from public.schedules
    where nullif(trim(sale_time), '') is null
       or nullif(trim(sale_time), '')::timestamptz is null
       or nullif(trim(url), '') is null
  ) then
    raise exception 'Cannot migrate schedules: sale_time or url is missing/invalid';
  end if;
end $$;

alter table public.schedules add column if not exists sale_at timestamptz;
alter table public.schedules add column if not exists created_at timestamptz not null default now();

update public.schedules
set sale_at = nullif(trim(sale_time), '')::timestamptz
where sale_at is null;

alter table public.schedules alter column sale_at set not null;
alter table public.schedules alter column name set not null;
alter table public.schedules alter column site set not null;
alter table public.schedules alter column url set not null;
alter table public.schedules alter column status set default 'active';

alter table public.schedules drop column if exists sale_time;
alter table public.schedules drop column if exists buyer_name;
alter table public.schedules drop column if exists target_id;
alter table public.schedules drop column if exists created_time;
alter table public.schedules drop column if exists reminders;

alter table public.schedules enable row level security;
revoke all on public.schedules from anon, authenticated;

create unique index if not exists schedules_active_url_sale_at_uidx
  on public.schedules (lower(url), sale_at)
  where status = 'active';

create table if not exists public.schedule_reminders (
  id bigint generated by default as identity primary key,
  schedule_id text not null references public.schedules(id) on delete cascade,
  offset_minutes integer not null check (offset_minutes in (1440, 60, 30, 15, 5)),
  due_at timestamptz not null,
  status text not null default 'pending' check (status in ('pending', 'processing', 'sent', 'failed', 'skipped')),
  attempt_count integer not null default 0 check (attempt_count between 0 and 5),
  next_attempt_at timestamptz not null,
  claimed_at timestamptz,
  sent_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  unique (schedule_id, offset_minutes)
);

create index if not exists schedule_reminders_due_idx
  on public.schedule_reminders (next_attempt_at, due_at)
  where status in ('pending', 'failed');

alter table public.schedule_reminders enable row level security;
revoke all on public.schedule_reminders from anon, authenticated;

create or replace function public.create_ticket_schedule(
  p_id text,
  p_name text,
  p_site text,
  p_url text,
  p_sale_at timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if p_sale_at <= now() or p_sale_at > now() + interval '2 years' then
    raise exception 'sale_at must be in the next two years';
  end if;

  insert into public.schedules (id, name, site, url, sale_at, status)
  values (p_id, trim(p_name), trim(p_site), trim(p_url), p_sale_at, 'active');

  insert into public.schedule_reminders (schedule_id, offset_minutes, due_at, next_attempt_at)
  select p_id, offset_minutes, p_sale_at - make_interval(mins => offset_minutes), p_sale_at - make_interval(mins => offset_minutes)
  from unnest(array[1440, 60, 30, 15, 5]) as offset_minutes;

  select to_jsonb(s) || jsonb_build_object(
    'schedule_reminders', coalesce((
      select jsonb_agg(to_jsonb(r) order by r.offset_minutes desc)
      from public.schedule_reminders r where r.schedule_id = s.id
    ), '[]'::jsonb)
  ) into result
  from public.schedules s where s.id = p_id;

  return result;
end;
$$;

revoke all on function public.create_ticket_schedule(text, text, text, text, timestamptz) from public, anon, authenticated;
grant execute on function public.create_ticket_schedule(text, text, text, text, timestamptz) to service_role;

create or replace function public.claim_ticket_reminders(p_limit integer default 20)
returns table (
  reminder_id bigint,
  schedule_id text,
  event_name text,
  event_site text,
  event_url text,
  sale_at timestamptz,
  offset_minutes integer,
  attempt_count integer
)
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.schedule_reminders
  set status = 'failed', claimed_at = null, next_attempt_at = now()
  where status = 'processing' and claimed_at < now() - interval '5 minutes' and attempt_count < 5;

  update public.schedule_reminders r
  set status = 'skipped', last_error = 'Reminder became stale before delivery'
  from public.schedules s
  where r.schedule_id = s.id
    and r.status in ('pending', 'failed')
    and (s.status <> 'active' or s.sale_at <= now() or r.due_at < now() - interval '10 minutes');

  return query
  with candidates as (
    select r.id
    from public.schedule_reminders r
    join public.schedules s on s.id = r.schedule_id
    where r.status in ('pending', 'failed')
      and r.attempt_count < 5
      and r.next_attempt_at <= now()
      and r.due_at <= now()
      and r.due_at >= now() - interval '10 minutes'
      and s.status = 'active'
      and s.sale_at > now()
    order by r.due_at
    for update of r skip locked
    limit greatest(1, least(p_limit, 100))
  ), claimed as (
    update public.schedule_reminders r
    set status = 'processing', claimed_at = now(), attempt_count = r.attempt_count + 1
    from candidates c
    where r.id = c.id
    returning r.*
  )
  select c.id, s.id, s.name, s.site, s.url, s.sale_at, c.offset_minutes, c.attempt_count
  from claimed c
  join public.schedules s on s.id = c.schedule_id;
end;
$$;

revoke all on function public.claim_ticket_reminders(integer) from public, anon, authenticated;
grant execute on function public.claim_ticket_reminders(integer) to service_role;
